esphome:
  platformio_options:
    build_flags:
      - "-O3"
      - "-DHP_PROTOCOL=${comfortzone_protocol_version}"

external_components:
  - source:
      type: git
      url: https://github.com/vinnyspb/esphome-comfortzone
      ref: ${git_branch}
    components: [ comfortzone ]

# Tracks the current offset of the indoor temperature sensor
globals:
  - id: te3_offset
    type: float
    restore_value: yes
    initial_value: '0.0'

uart:
  id: uart_bus
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  baud_rate: 19200
  data_bits: 8
  parity: NONE
  stop_bits: 1

comfortzone:
  re_de_pin: ${re_de_pin}
  te3_offset_global_id: te3_offset

sensor:
  - platform: comfortzone
    fan_time_to_filter_change:
      name: "Days until filter change"
    te0_outdoor_temp:
      name: "Outdoor temperature"
    te1_flow_water:
      name: "Flow water temperature"
    te2_return_water:
      name: "Return water temperature"
    te3_indoor_temp:
      name: "Indoor temperature"
    te4_hot_gas_temp:
      name: "Hot gas temperature"
    te5_exchanger_out:
      name: "Exchanger out temperature"
    te6_evaporator_in:
      name: "Evaporator in temperature"
    te7_exhaust_air:
      name: "Exhaust air temperature"
    te24_hot_water_temp:
      name: "Hot water temperature"
    expansion_valve_calculated_setting:
      name: "Expansion valve calculated setting"
    expansion_valve_temperature_difference:
      name: "Expansion valve temperature difference"
    current_compressor_frequency:
      name: "Current compressor frequency"
    current_compressor_power:
      name: "Current compressor power"
    current_compressor_additional_power:
      name: "Current compressor additional power"
    current_compressor_total_power:
      name: "Current compressor total power"
    current_compressor_input_power:
      name: "Current compressor input power"
      id: current_compressor_input_power
    current_compressor_heating_input_power:
      name: "Current compressor heating input power"
      id: current_compressor_heating_input_power
    current_compressor_water_input_power:
      name: "Current compressor water input power"
      id: current_compressor_water_input_power
    compressor_energy:
      name: "Compressor energy"
    add_energy:
      name: "Additional energy"
    hot_water_energy:
      name: "Hot water energy"
    compressor_runtime:
      name: "Compressor runtime"
    total_runtime:
      name: "Total runtime"
    room_heating_setting:
      name: "Room heating setting"
    hot_water_setting:
      name: "Hot water setting"
    fan_speed_duty:
      name: "Fan speed duty"
    hot_water_calculated_setting:
      name: "Hot water calculated setting"
    heating_cop:
      name: "Heating CoP"
    water_cop:
      name: "Hot Water CoP"
    te3_indoor_temp_offset:
      name: "Indoor temperature sensor offset"
    target_flow_water_temperature:
      name: "Target flow water temperature"
  - platform: total_daily_energy
    name: "Total Daily Input Energy"
    power_id: current_compressor_input_power
  - platform: total_daily_energy
    name: "Total Daily Heating Input Energy"
    power_id: current_compressor_heating_input_power
  - platform: total_daily_energy
    name: "Total Daily Water Input Energy"
    power_id: current_compressor_water_input_power

binary_sensor:
  - platform: comfortzone
    filter_alarm:
      name: "Filter alarm"
    hot_water_production:
      name: "Hot water production"
    room_heating_in_progress:
      name: "Room heating in progress"
    additional_power_enabled:
      name: "Additional power enabled"
    defrost_enabled:
      name: "Defrost enabled"
    extra_hot_water_setting:
      name: "Extra hot water setting"

text_sensor:
  - platform: comfortzone
    compressor_activity:
      name: "Compressor activity"
    mode:
      name: "Mode"
    fan_speed:
      name: "Fan speed"
    hot_water_priority_setting:
      name: "Hot water priority setting"

climate:
  - platform: comfortzone
    heatpump_climate:
      name: "ComfortZone EX50 heating"
    water_heater_climate:
      name: "ComfortZone EX50 hot water"
      visual:
        min_temperature: 30
        max_temperature: 65

# Needed to keep track of sensor offset changes
time:
  - platform: sntp
    id: sntp_time

# Enables exposure of built-in services to Home Assistant
api:
